### ISSUE TITLE
pytest-html is trying to encode my data inappropriately

### ISSUE THREAD

**Issue by birdsarah** [davehunt/pytest-html#27] opened 2016-01-25 21:55 UTC
I'm using:
* pytest-selenium 1.1
* pytest-html 1.7
* selenium 2.49.2

I get the following error on a test fail:

````python
INTERNALERROR>     data = b64encode(content.encode(charset)).decode('ascii')
INTERNALERROR> AttributeError: 'bytes' object has no attribute 'encode'
> /Users/caged/miniconda3/envs/bokeh_34/lib/python3.4/site-packages/pytest_html-1.7-py3.4.egg/pytest_html/plugin.py(74)data_uri()
-> data = b64encode(content.encode(charset)).decode('ascii')


 72     def data_uri(content, mime_type='text/plain', charset='utf-8'):
 73         if PY3:
 74  ->         data = b64encode(content.encode(charset)).decode('ascii')
 75         else:
 76             data = b64encode(content)
 77         return 'data:{0};charset={1};base64,{2}'.format(mime_type, charset, data)
````

When in pdb, just running `b64encode(content)` works great - maybe PY3 check isn't quite right? Could we check what content is instead?

**Comment by davehunt** [comment] 2016-01-26 12:22
@birdsarah could you paste more of your stack trace? I'm most interested in what content is, and where it's being provided. I assume this is one of the debug items from pytest-selenium but it's not clear which one. Note that pytest-selenium doesn't officially support Python 3.x, and it's possible it could be fixed there. That said, we probably want to support `bytes` objects in pytest-html too.

**Comment by davehunt** [comment] 2016-01-26 13:29
I was able to replicate this, and have addressed it in #28. I am still interested in where this bytes object is being created though, if you could provide more information.

**Comment by davehunt** [comment] 2016-01-28 18:56
My guess is that this is caused by pytest-selenium encoding [here](https://github.com/davehunt/pytest-selenium/blob/db3f61afa2477735a6ec8bf29737e011fd7bdc9b/pytest_selenium/pytest_selenium.py#L153) and [here](https://github.com/davehunt/pytest-selenium/blob/db3f61afa2477735a6ec8bf29737e011fd7bdc9b/pytest_selenium/pytest_selenium.py#L226). This is necessary for Python 2.x but perhaps not for 3.x? @The-Compiler do you think this should be fixed in pytest-selenium to just pass the unicode object instead of encoding it first?

**Comment by The-Compiler** [comment] 2016-01-28 19:38
As per the "[unicode sandwich](http://nedbatchelder.com/text/unipain.html)" concept (decode/encode at the borders, deal with unicode everywhere else), I think that'd make sense, yeah.

**Comment by davehunt** [comment] 2016-02-18 17:58
Closing as the content should be encoded properly before sending it to pytest-html. I'll be fixing this in pytest-selenium.

**Closed by davehunt** 2016-02-18 17:58 UTC
